version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building the app...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
